# Generated by Django 5.1.1 on 2024-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
